ID = ''                     # S3 ID
KEY = ''                    # S3 key
BUCKET = ''                 # S3 bucket (needs to be lowercase)
S3URL = 'https://s3-eu-west-1.amazonaws.com/%s/' % BUCKET
DB_HOST = 'localhost'       # can also be fqdn
DB_NAME = ''                # DB Name (postgresql)
DB_USER = ''                # DB User name
DB_PASSWD = ''              # DB Password
DB_PHOTOTABLE = ''          # table name
KEEP_EXIF = True|False      # keep exif header in saved photos
